### ISSUE TITLE
Deploy monitoring_check::cluster to a wider net

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/puppet-monitoring_check#30]
Now that we can, we are ready to test the cluster check on more boxes.

This ticket is to build the puppet code to contain all these checks, and the future pieces (cluster/watchdog/server-side)

cc @georgebashi @somic @trumpcard @keymone @lmovsesjan

The acceptance criteria is when we have a place in puppet to put these things, and the first big check is deployed. I think per-module hieradata is a good way to contain these kind of things. And maybe do a hiera merge so we can say thing like:

```
common:
cluster_checks:
  - apache:
  page: true
 - disk_root

stage:
cluster_checks:
 - apache:
 page:false
- apache_ram:
- apache_cpu

prod:
cluster_check:
- apache_ram:
- apache_cpu
- google_connectiviy
```

And with the merge these will all get consumed together instead of overwritten on a per-whatever basis.
